import { TemplateData } from './template-types';

// Estimate templates data
export const estimateTemplates: TemplateData[] = [
  {
    id: '1',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '30/12/2024',
  },
  {
    id: '2',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Full Home Build/Addition',
    categoryColor: '#10B981',
    createdDate: '29/12/2024',
  },
  {
    id: '3',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Full Home Build/Addition',
    categoryColor: '#10B981',
    createdDate: '28/12/2024',
  },
  {
    id: '4',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '27/12/2024',
  },
  {
    id: '5',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '25/12/2024',
  },
  {
    id: '6',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '20/12/2024',
  },
  {
    id: '7',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '15/12/2024',
  },
  {
    id: '8',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '10/12/2024',
  },
  {
    id: '9',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '08/12/2024',
  },
  {
    id: '10',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '07/12/2024',
  },
  {
    id: '11',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '06/12/2024',
  },
  {
    id: '12',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '05/12/2024',
  },
  {
    id: '13',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Commercial',
    category: 'Office Space',
    categoryColor: '#3B82F6',
    createdDate: '04/12/2024',
  },
  {
    id: '14',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Commercial',
    category: 'Retail Space',
    categoryColor: '#EF4444',
    createdDate: '03/12/2024',
  },
  {
    id: '15',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Kitchen Remodel',
    categoryColor: '#F97316',
    createdDate: '02/12/2024',
  },
];

// Option bid templates data
export const optionBidTemplates: TemplateData[] = [
  {
    id: '16',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Shower Install',
    material: 'Shower',
    createdDate: '30/12/2024',
  },
  {
    id: '17',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Kitchen Remodel',
    material: 'Cabinets',
    createdDate: '29/12/2024',
  },
  {
    id: '18',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Bathroom Renovation',
    material: 'Tiles',
    createdDate: '28/12/2024',
  },
  {
    id: '19',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Flooring Installation',
    material: 'Hardwood',
    createdDate: '27/12/2024',
  },
  {
    id: '20',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Roofing',
    material: 'Shingles',
    createdDate: '25/12/2024',
  },
  {
    id: '21',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Electrical Work',
    material: 'Wiring',
    createdDate: '20/12/2024',
  },
  {
    id: '22',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Plumbing',
    material: 'Pipes',
    createdDate: '15/12/2024',
  },
  {
    id: '23',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Painting',
    material: 'Paint',
    createdDate: '10/12/2024',
  },
  {
    id: '24',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'HVAC Installation',
    material: 'Ductwork',
    createdDate: '08/12/2024',
  },
  {
    id: '25',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Landscaping',
    material: 'Plants',
    createdDate: '07/12/2024',
  },
  {
    id: '26',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Deck Building',
    material: 'Wood',
    createdDate: '06/12/2024',
  },
  {
    id: '27',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Window Installation',
    material: 'Glass',
    createdDate: '05/12/2024',
  },
];

// Tools templates data
export const toolsTemplates: TemplateData[] = [
  {
    id: '28',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Power Tools',
    material: 'Drills',
    createdDate: '30/12/2024',
  },
  {
    id: '29',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Hand Tools',
    material: 'Screwdrivers',
    createdDate: '29/12/2024',
  },
  {
    id: '30',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Measuring Tools',
    material: 'Tape Measures',
    createdDate: '28/12/2024',
  },
  {
    id: '31',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Safety Equipment',
    material: 'Hard Hats',
    createdDate: '27/12/2024',
  },
  {
    id: '32',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Cutting Tools',
    material: 'Saws',
    createdDate: '25/12/2024',
  },
];

// Disclaimers templates data
export const disclaimersTemplates: TemplateData[] = [
  {
    id: '33',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Liability Waiver',
    material: 'Legal Document',
    createdDate: '30/12/2024',
  },
  {
    id: '34',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Warranty Terms',
    material: 'Contract',
    createdDate: '29/12/2024',
  },
  {
    id: '35',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Safety Notice',
    material: 'Warning',
    createdDate: '28/12/2024',
  },
];

// Archive templates data
export const archiveTemplates: TemplateData[] = [
  {
    id: '36',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '01/12/2024',
  },
  {
    id: '37',
    type: 'option-bid',
    templateName: 'Template Name',
    service: 'Old Service',
    material: 'Old Material',
    createdDate: '30/11/2024',
  },
  {
    id: '38',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Old Tools',
    material: 'Old Equipment',
    createdDate: '29/11/2024',
  },
  {
    id: '39',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Old Disclaimer',
    material: 'Old Document',
    createdDate: '28/11/2024',
  },
];
