import { TemplateData } from './template-types';

// Estimate templates data
export const estimateTemplates: TemplateData[] = [
  {
    id: '1',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '30/12/2024',
  },
  {
    id: '2',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Full Home Build/Addition',
    categoryColor: '#10B981',
    createdDate: '29/12/2024',
  },
  {
    id: '3',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Full Home Build/Addition',
    categoryColor: '#10B981',
    createdDate: '28/12/2024',
  },
  {
    id: '4',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '27/12/2024',
  },
  {
    id: '5',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '25/12/2024',
  },
  {
    id: '6',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '20/12/2024',
  },
  {
    id: '7',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '15/12/2024',
  },
  {
    id: '8',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '10/12/2024',
  },
  {
    id: '9',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Single/Multi Trade',
    categoryColor: '#F59E0B',
    createdDate: '08/12/2024',
  },
  {
    id: '10',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Exterior',
    categoryColor: '#F59E0B',
    createdDate: '07/12/2024',
  },
  {
    id: '11',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '06/12/2024',
  },
  {
    id: '12',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '05/12/2024',
  },
  {
    id: '13',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Commercial',
    category: 'Office Space',
    categoryColor: '#3B82F6',
    createdDate: '04/12/2024',
  },
  {
    id: '14',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Commercial',
    category: 'Retail Space',
    categoryColor: '#EF4444',
    createdDate: '03/12/2024',
  },
  {
    id: '15',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Kitchen Remodel',
    categoryColor: '#F97316',
    createdDate: '02/12/2024',
  },
];

// Service option templates data
export const serviceOptionTemplates: TemplateData[] = [
  {
    id: '1',
    type: 'service-option',
    templateName: 'Basic Service Options',
    createdDate: '30/12/2024',
    service: 'General',
    material: 'Standard',
  },
  {
    id: '2',
    type: 'service-option',
    templateName: 'Premium Service Options',
    createdDate: '29/12/2024',
    service: 'Premium',
    material: 'High-end',
  },
  {
    id: '3',
    type: 'service-option',
    templateName: 'Standard Service Options',
    createdDate: '28/12/2024',
    service: 'Standard',
    material: 'Standard',
  },
  {
    id: '4',
    type: 'service-option',
    templateName: 'Custom Service Options',
    createdDate: '27/12/2024',
    service: 'Custom',
    material: 'Custom',
  },
  {
    id: '5',
    type: 'service-option',
    templateName: 'Professional Service Options',
    createdDate: '26/12/2024',
    service: 'Professional',
    material: 'Professional',
  },
  {
    id: '6',
    type: 'service-option',
    templateName: 'Enterprise Service Options',
    createdDate: '25/12/2024',
    service: 'Enterprise',
    material: 'Enterprise',
  },
  {
    id: '7',
    type: 'service-option',
    templateName: 'Starter Service Options',
    createdDate: '24/12/2024',
    service: 'Starter',
    material: 'Starter',
  },
  {
    id: '8',
    type: 'service-option',
    templateName: 'Advanced Service Options',
    createdDate: '23/12/2024',
    service: 'Advanced',
    material: 'Advanced',
  },
  {
    id: '9',
    type: 'service-option',
    templateName: 'Expert Service Options',
    createdDate: '22/12/2024',
    service: 'Expert',
    material: 'Expert',
  },
  {
    id: '10',
    type: 'service-option',
    templateName: 'Master Service Options',
    createdDate: '21/12/2024',
    service: 'Master',
    material: 'Master',
  },
  {
    id: '11',
    type: 'service-option',
    templateName: 'Elite Service Options',
    createdDate: '20/12/2024',
    service: 'Elite',
    material: 'Elite',
  },
  {
    id: '12',
    type: 'service-option',
    templateName: 'Ultimate Service Options',
    createdDate: '19/12/2024',
    service: 'Ultimate',
    material: 'Ultimate',
  },
];

// Tools templates data
export const toolsTemplates: TemplateData[] = [
  {
    id: '28',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Power Tools',
    material: 'Drills',
    createdDate: '30/12/2024',
  },
  {
    id: '29',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Hand Tools',
    material: 'Screwdrivers',
    createdDate: '29/12/2024',
  },
  {
    id: '30',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Measuring Tools',
    material: 'Tape Measures',
    createdDate: '28/12/2024',
  },
  {
    id: '31',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Safety Equipment',
    material: 'Hard Hats',
    createdDate: '27/12/2024',
  },
  {
    id: '32',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Cutting Tools',
    material: 'Saws',
    createdDate: '25/12/2024',
  },
];

// Disclaimers templates data
export const disclaimersTemplates: TemplateData[] = [
  {
    id: '33',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Liability Waiver',
    material: 'Legal Document',
    createdDate: '30/12/2024',
  },
  {
    id: '34',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Warranty Terms',
    material: 'Contract',
    createdDate: '29/12/2024',
  },
  {
    id: '35',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Safety Notice',
    material: 'Warning',
    createdDate: '28/12/2024',
  },
];

// Archive templates data
export const archiveTemplates: TemplateData[] = [
  {
    id: '36',
    type: 'estimate',
    templateName: 'Template Name',
    propertyType: 'Residential',
    category: 'Interior',
    categoryColor: '#8B5CF6',
    createdDate: '01/12/2024',
  },
  {
    id: '37',
    type: 'service-option',
    templateName: 'Template Name',
    service: 'Old Service',
    material: 'Old Material',
    createdDate: '30/11/2024',
  },
  {
    id: '38',
    type: 'tools',
    templateName: 'Template Name',
    service: 'Old Tools',
    material: 'Old Equipment',
    createdDate: '29/11/2024',
  },
  {
    id: '39',
    type: 'disclaimer',
    templateName: 'Template Name',
    service: 'Old Disclaimer',
    material: 'Old Document',
    createdDate: '28/11/2024',
  },
];
