import { FIVE_BOX_SLUGS } from './five-box-slug-constants';
import { FiveBoxItem } from './five-box-types';

export const FIVE_BOX_DATA: FiveBoxItem[] = [
  {
    id: '01',
    number: '01',
    color: '#34AD4426',
    textColor: '#34AD44',
    title: 'General Information',
    description:
      'Includes name, email, phone number, and basic contact details.',
    enabled: true,
    slug: FIVE_BOX_SLUGS.GENERAL_INFORMATION,
    isRequired: true,
    isCompleted: false,
    order: 1,
    icon: 'user',
    formFields: ['name', 'email', 'phone', 'address'],
  },
  {
    id: '02',
    number: '02',
    color: '#1A57BF1A',
    textColor: '#1A57BF',
    title: 'Property Information',
    description: 'Includes home size, number of BHKs, and floor count.',
    enabled: true,
    slug: FIVE_BOX_SLUGS.PROPERTY_INFORMATION,
    isRequired: true,
    isCompleted: false,
    order: 2,
    icon: 'home',
    formFields: ['propertyType', 'size', 'bhk', 'floorCount'],
  },
  {
    id: '03',
    number: '03',
    color: '#00A8BF26',
    textColor: '#00A8BF',
    title: 'Project Information',
    description:
      'Includes work type (interior, exterior, etc.) and service scope.',
    enabled: true,
    slug: FIVE_BOX_SLUGS.PROJECT_INFORMATION,
    isRequired: true,
    isCompleted: false,
    order: 3,
    icon: 'project',
    formFields: ['workType', 'serviceScope', 'timeline'],
  },
  {
    id: '04',
    number: '04',
    color: '#90C91D26',
    textColor: '#90C91D',
    title: 'Category',
    description: 'Includes project name, location, and key contacts.',
    enabled: true,
    slug: FIVE_BOX_SLUGS.CATEGORY,
    isRequired: true,
    isCompleted: false,
    order: 4,
    icon: 'category',
    formFields: ['projectName', 'location', 'contacts'],
  },
  {
    id: '05',
    number: '05',
    color: '#D4323226',
    textColor: '#D43232',
    title: 'Estimation',
    description: 'Includes pricing based on size, scope, and type of work.',
    enabled: true,
    slug: FIVE_BOX_SLUGS.ESTIMATION,
    isRequired: true,
    isCompleted: false,
    order: 5,
    icon: 'calculator',
    formFields: ['budget', 'pricing', 'paymentTerms'],
  },
];
