import { ToolDetailData } from './types';

export const availableToolData: ToolDetailData[] = [
  {
    id: '1',
    toolId: '11345',
    barcode: 'QR12345',
    returnedBy: {
      name: 'Available',
      avatar: '/images/avatars/avatar-1.png',
    },
    employeeType: 'Ready',
    assignedJob: 'Not Assigned',
    dueDate: '-',
    returnedDate: '-',
    condition: 'Good',
    assignedStatus: 'Available',
  },
  {
    id: '2',
    toolId: '10345',
    barcode: 'QR12346',
    returnedBy: {
      name: 'Available',
      avatar: '/images/avatars/avatar-2.png',
    },
    employeeType: 'Ready',
    assignedJob: 'Not Assigned',
    dueDate: '-',
    returnedDate: '-',
    condition: 'Excellent',
    assignedStatus: 'Available',
  },
  {
    id: '3',
    toolId: '12745',
    barcode: 'QR12347',
    returnedBy: {
      name: 'Available',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Ready',
    assignedJob: 'Not Assigned',
    dueDate: '-',
    returnedDate: '-',
    condition: 'Decent',
    assignedStatus: 'Available',
  },
  {
    id: '4',
    toolId: '12344',
    barcode: 'QR12386',
    returnedBy: {
      name: 'Available',
      avatar: '/images/avatars/avatar-4.png',
    },
    employeeType: 'Ready',
    assignedJob: 'Not Assigned',
    dueDate: '-',
    returnedDate: '-',
    condition: 'Good',
    assignedStatus: 'Available',
  },
  {
    id: '5',
    toolId: '12746',
    barcode: 'QR12348',
    returnedBy: {
      name: 'Available',
      avatar: '/images/avatars/avatar-5.png',
    },
    employeeType: 'Ready',
    assignedJob: 'Not Assigned',
    dueDate: '-',
    returnedDate: '-',
    condition: 'Excellent',
    assignedStatus: 'Available',
  },
];

export const assignedToolData: ToolDetailData[] = [
  {
    id: '1',
    toolId: '11345',
    barcode: 'QR12345',
    returnedBy: {
      name: 'Liam Anderson',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Temporary',
  },
  {
    id: '2',
    toolId: '10345',
    barcode: 'QR12346',
    returnedBy: {
      name: 'Emma Thompson',
      avatar: '/images/avatars/avatar-4.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Excellent',
    assignedStatus: 'Temporary',
  },
  {
    id: '3',
    toolId: '12745',
    barcode: 'QR12347',
    returnedBy: {
      name: 'Noah Johnson',
      avatar: '/images/avatars/avatar-5.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Decent',
    assignedStatus: 'Permanent',
  },
  {
    id: '4',
    toolId: '12344',
    barcode: 'QR12386',
    returnedBy: {
      name: 'Olivia Martinez',
      avatar: '/images/avatars/avatar-6.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Permanent',
  },
  {
    id: '5',
    toolId: '20345',
    barcode: 'QR12655',
    returnedBy: {
      name: 'Ava Robinson',
      avatar: '/images/avatars/avatar-7.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Excellent',
    assignedStatus: 'Temporary',
  },
  {
    id: '6',
    toolId: '20345',
    barcode: 'QR12445',
    returnedBy: {
      name: 'Ethan Clark',
      avatar: '/images/avatars/avatar-8.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Permanent',
  },
  {
    id: '7',
    toolId: '12345',
    barcode: 'QR12645',
    returnedBy: {
      name: 'Sophia Lewis',
      avatar: '/images/avatars/avatar-1.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Temporary',
  },
  {
    id: '8',
    toolId: '20345',
    barcode: 'QR14345',
    returnedBy: {
      name: 'Mason Walker',
      avatar: '/images/avatars/avatar-2.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Temporary',
  },
  {
    id: '9',
    toolId: '12345',
    barcode: 'QR17345',
    returnedBy: {
      name: 'Isabella Hall',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Decent',
    assignedStatus: 'Permanent',
  },
  {
    id: '10',
    toolId: '12345',
    barcode: 'QR12345',
    returnedBy: {
      name: 'Guy Hawkins',
      avatar: '/images/avatars/avatar-4.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '26/08/2024',
    returnedDate: '26/08/2024',
    condition: 'Good',
    assignedStatus: 'Temporary',
  },
];

export const maintenanceToolData: ToolDetailData[] = [
  {
    id: '1',
    toolId: '11345',
    barcode: 'QR12345',
    returnedBy: {
      name: 'Liam Anderson',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Jam',
    assignedStatus: 'Maintenance',
  },
  {
    id: '2',
    toolId: '10345',
    barcode: 'QR12346',
    returnedBy: {
      name: 'Emma Thompson',
      avatar: '/images/avatars/avatar-4.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Overheat',
    assignedStatus: 'Maintenance',
  },
  {
    id: '3',
    toolId: '12745',
    barcode: 'QR12347',
    returnedBy: {
      name: 'Noah Johnson',
      avatar: '/images/avatars/avatar-5.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Vibration',
    assignedStatus: 'Maintenance',
  },
  {
    id: '4',
    toolId: '12344',
    barcode: 'QR12386',
    returnedBy: {
      name: 'Olivia Martinez',
      avatar: '/images/avatars/avatar-6.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Stall',
    assignedStatus: 'Maintenance',
  },
  {
    id: '5',
    toolId: '20345',
    barcode: 'QR12655',
    returnedBy: {
      name: 'Ava Robinson',
      avatar: '/images/avatars/avatar-7.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Noise',
    assignedStatus: 'Maintenance',
  },
  {
    id: '6',
    toolId: '20345',
    barcode: 'QR12445',
    returnedBy: {
      name: 'Ethan Clark',
      avatar: '/images/avatars/avatar-8.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Leak',
    assignedStatus: 'Maintenance',
  },
  {
    id: '7',
    toolId: '12345',
    barcode: 'QR12645',
    returnedBy: {
      name: 'Sophia Lewis',
      avatar: '/images/avatars/avatar-1.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Leak',
    assignedStatus: 'Maintenance',
  },
  {
    id: '8',
    toolId: '20345',
    barcode: 'QR14345',
    returnedBy: {
      name: 'Mason Walker',
      avatar: '/images/avatars/avatar-2.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Short',
    assignedStatus: 'Maintenance',
  },
  {
    id: '9',
    toolId: '12345',
    barcode: 'QR17345',
    returnedBy: {
      name: 'Isabella Hall',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Poor',
    issue: 'Short',
    assignedStatus: 'Maintenance',
  },
];

export const lostToolData: ToolDetailData[] = [
  {
    id: '1',
    toolId: '11345',
    barcode: 'QR12345',
    returnedBy: {
      name: 'Liam Anderson',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '2',
    toolId: '10345',
    barcode: 'QR12346',
    returnedBy: {
      name: 'Emma Thompson',
      avatar: '/images/avatars/avatar-4.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '3',
    toolId: '12745',
    barcode: 'QR12347',
    returnedBy: {
      name: 'Noah Johnson',
      avatar: '/images/avatars/avatar-5.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '4',
    toolId: '12344',
    barcode: 'QR12386',
    returnedBy: {
      name: 'Olivia Martinez',
      avatar: '/images/avatars/avatar-6.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '5',
    toolId: '20345',
    barcode: 'QR12655',
    returnedBy: {
      name: 'Ava Robinson',
      avatar: '/images/avatars/avatar-7.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '6',
    toolId: '20345',
    barcode: 'QR12445',
    returnedBy: {
      name: 'Ethan Clark',
      avatar: '/images/avatars/avatar-8.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '7',
    toolId: '12345',
    barcode: 'QR12645',
    returnedBy: {
      name: 'Sophia Lewis',
      avatar: '/images/avatars/avatar-1.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '8',
    toolId: '20345',
    barcode: 'QR14345',
    returnedBy: {
      name: 'Mason Walker',
      avatar: '/images/avatars/avatar-2.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
  {
    id: '9',
    toolId: '12345',
    barcode: 'QR17345',
    returnedBy: {
      name: 'Isabella Hall',
      avatar: '/images/avatars/avatar-3.png',
    },
    employeeType: 'Employees',
    assignedJob: 'Job#456 Downtown Project',
    dueDate: '30/08/2024',
    returnedDate: '30/08/2024',
    condition: 'Unknown',
    assignedStatus: 'Lost',
  },
];
